### ISSUE TITLE
Allow changing config path in GUI

### ISSUE THREAD

**Issue by Riquet** [OpenMediaVault-Plugin-Developers/openmediavault-syncthing#2]
Hi,

I have conflicts with sync ".config/" directory.

".config/" is in home directory by default for all users, and my users use SyncTrayzor on their windows machine where .config/ is also in their Windows home dir.

Is it possible to add a specific location into the GUI to set this .config directory for each user and use it in init.d to the syncthing parameter "-home"

Thanks in advance.

**Comment by ryecoaaron** [comment]
When I said "pull request" in the forum, that meant you could write the code and submit it.  I going to mark this as wontfix since I don't have the time and there isn't enough demand for it.
