### ISSUE TITLE
Error - 'inotify' does not exist

### ISSUE THREAD

**Issue by rkburnside** [OpenMediaVault-Plugin-Developers/openmediavault-syncthing#3]
I am unable to add any syncthing users with the error below (OMV won't let me save a user with this error). PLEASE help.

I downloaded and installed OMV on a raspberry pi 3 today and added the syncthing plugin. When I try to "Add" a user, the following error pops up:

`The property 'inotify' does not exist in the model 'conf.service.syncthing'.`

Is this error being caused by your recent commit or is this an error on my side? I've tried toggling the "Inotify" option when adding a user and the same error pops up.

The "Details" button shows the following:

`Error #0:
exception 'OMV\AssertException' with message 'The property 'inotify' does not exist in the model 'conf.service.syncthing'.' in /usr/share/php/openmediavault/config/configobject.inc:71
Stack trace:
#0 /usr/share/php/openmediavault/config/configobject.inc(186): OMV\Config\ConfigObject->assertExists('inotify')
#1 /usr/share/php/openmediavault/config/configobject.inc(271): OMV\Config\ConfigObject->set('inotify', true, true)
#2 /usr/share/php/openmediavault/config/configobject.inc(233): OMV\Config\ConfigObject->setFlatAssoc(Array, true, false)
#3 /usr/share/openmediavault/engined/rpc/syncthing.inc(77): OMV\Config\ConfigObject->setAssoc(Array)
#4 [internal function]: OMVRpcServiceSyncthing->setUser(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setUser', Array, Array)
#7 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Syncthing', 'setUser', Array, Array, 1)
#8 {main}`

**Comment by ryecoaaron** [comment]
The inotify option was removed.  Your browser must still have it cached.  Clear your browser cache.

**Comment by rkburnside** [comment]
that was it! thanks!
